stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/house.csv
      - params.yaml
    outs:
      - data/processed_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed_data.csv
      - params.yaml
    outs:
      - models/linear.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/linear.pkl
      - data/test.csv
      - params.yaml
    metrics:
      - reports/metrics.json
