dataset:
  path: data/house.csv
  processed_data: data/processed_data.csv
  test: data/test.csv

train: 
  test_size: 0.2
  random state: 42

model:
  linear: models/linear.pkl

reports:
  metrics: reports/metrics.json